import mysql.connector as sql
sqlcon=sql.connect(host='localhost',user='root',password='*********',database='pdtmgmt')
sqlcur=sqlcon.cursor()
print("\t\t...........................................................................")
print("\t\t\t\t\t    Welcome to Dawa Pharma")
print("\t\t...........................................................................")
ch=int(input("\t\tPress 1 for Login or Press 2 for SignUp : "))
if ch==1:
    print("\n\t\t\t\t\t\tUser Login")
    uid=input("\n\t\t\tEnter UserId     :   ")
    pas=input("\t\t\tEnter Password   :   ")
    q="select userid,password from users where userid='{}' and password='{}'".format(uid,pas)
    sqlcur.execute(q)
    data=sqlcur.fetchall()
    if data==[]:
        print("Login Fail due to invalid entry!")
    else:
        print("\t\t...........................................................................")
        print("\t\t\t\tWelcome to Dawa Pharma Management System")
        print("\t\t...........................................................................")
        print("\t\tPress 1 for New Entry of product      : ")
        print("\t\tPress 2 for searching product         : ")
        print("\t\tPress 3 for updating  product details : ")
        print("\t\tPress 4 for deleting product record   : ")
        print("\t\tPress 5 for customer related works    : ")
        print("\t\tPress 6 for exit                      : ")
        opt=int(input("\t\tEnter your choice : "))
        if opt==1:
            print("\n\t\t\t\t\t\tEnter product details")
            pid=input("\t\tEnter Product Id            : ")
            pname=input("\t\tEnter product name          : ")
            dom=input("\t\tEnter Date of Manufacturing : ")
            doe=input("\t\tEnter Date of expiry        : ")
            bn=int(input("\t\tEnter Batch No.             : "))
            pop=int(input("\t\tEnter price of product      : "))
            cid=input("\t\tEnter the Company Id        : ")
            q="insert into product values('{}','{}','{}','{}','{}','{}','{}')".format(pid,pname,dom,doe,bn,pop,cid)
            sqlcur.execute(q)
            sqlcon.commit()
            print("Product record saved successfully!")
            print("Thanks for using Dawa Pharma Management System!")
        elif opt==2:
            pid=input("\t\tEnter Product Id        : ")
            q="select * from product where pid='{}'".format(pid) 
            sqlcur.execute(q)
            data=sqlcur.fetchall()
            if data==[]:
                print("Record not found!")
                print("Thanks for using Dawa Pharma Management System!")
            else:
                print("\n\t\t Record found!",data)
        elif opt==3:
            chh=int(input("\t\tpress 1 to update batch_no. or 2 to update pname : "))
            if chh==1:
                pid=input("\t\tEnter product Id to update record      : ")
                nbn=int(input("Enter New Batch No.  : "))
                q="update product set batch_no='{}' where pid='{}'".format(nbn,pid)
                sqlcur.execute(q)
                sqlcon.commit()
                print("Product batch_no. updated successfully!")
                print("Thanks for using Dawa Pharma Management System!")
            elif chh==2:
                pid=input("\t\tEnter product Id to update record      : ")
                npn=int(input("Enter New Product Name  : "))
                q="update product set pname='{}' where pid='{}'".format(npn,pid)
                sqlcur.execute(q)
                sqlcon.commit()
                print("Product name updated successfully!")
                print("Thanks for using Dawa Pharma Management System!")
            else:
                print("Choice is invalid!")
                print("Thanks for using Dawa Pharma Management System!")
                exit(1)
        elif opt==4:
            pid=input("\t\tEnter Product Id to delete record      : ")
            q="delete from product where pid='{}'".format(pid)
            sqlcur.execute(q)
            sqlcon.commit()
            print("Product record of pid",pid,"has been deleted successfully!")
            print("Thanks for using Dawa Pharma Management System!")
        elif opt==5:
            print("\t\tPress 1 for New order                 : ")
            print("\t\tPress 2 for searching order           : ")
            print("\t\tPress 3 for updating  order details   : ")
            print("\t\tPress 4 for deleting order record     : ")
            print("\t\tPress 5 for exit                      : ")
            cho=int(input("\t\tEnter your choice : "))
            if cho==1:
                print("\n\t\t\t\t\t\tEnter order details")
                cuid=input("\t\tEnter Customer Id           : ")
                cuname=input("\t\tEnter Customer name          : ")
                city=input("\t\tEnter city name             : ")
                ph_no=input("\t\tEnter Phone No.             : ")
                email_id=input("\t\tEnter Email-Id               : ")
                order_dt=input("\t\tEnter order date             : ")
                pid=input("\t\tEnter Product Id            : ")
                pdt_qty=int(input("\t\tEnter product quantity       : "))
                cid=input("\t\tEnter the Company Id        : ")
                q="insert into customer values('{}','{}','{}','{}','{}','{}','{}','{}','{}')".format(cuid,cuname,city,ph_no,email_id,order_dt,pid,pdt_qty,cid)
                sqlcur.execute(q)
                sqlcon.commit()
                print("Customer order saved successfully!")
                print("Thanks for using Dawa Pharma Management System!")
            elif cho==2:
                cuid=input("\t\tEnter Customer Id        : ")
                q="select * from customer where cuid='{}'".format(cuid) 
                sqlcur.execute(q)
                data=sqlcur.fetchall()
                if data==[]:
                    print("Record not found!")
                    print("Thanks for using Dawa Pharma Management System!")
                else:
                    print("\n\t\t Record found!",data)
            elif cho==3:
                print("\t\tPress 1 for updating city name        : ")
                print("\t\tPress 2 for updating Phone No.        : ")
                print("\t\tPress 3 for updating Email-Id         : ")
                print("\t\tPress 4 for updating product quantity : ")
                choi=int(input("\t\tEnter your choice : "))
                if choi==1:
                    cuid=input("\t\tEnter Customer Id to update record      : ")
                    ncn=input("\t\tEnter New City Name                     : ")
                    q="update customer set city='{}' where cuid='{}'".format(ncn,cuid)
                    sqlcur.execute(q)
                    sqlcon.commit()
                    print("Customer city name updated successfully!")
                    print("Thanks for using Dawa Pharma Management System!")
                elif choi==2:
                    cuid=input("\t\tEnter Customer Id to update record      : ")
                    npn=int(input("\t\tEnter New Phone No.                     : "))
                    q="update customer set ph_no='{}' where cuid='{}'".format(npn,cuid)
                    sqlcur.execute(q)
                    sqlcon.commit()
                    print("Customer Phone No. updated successfully!")
                    print("Thanks for using Dawa Pharma Management System!")
                elif choi==3:
                    cuid=input("\t\tEnter Customer Id to update record      : ")
                    neid=input("\t\tEnter New Email-Id                      : ")
                    q="update customer set email_id='{}' where cuid='{}'".format(neid,cuid)
                    sqlcur.execute(q)
                    sqlcon.commit()
                    print("Customer Email-Id updated successfully!")
                    print("Thanks for using Dawa Pharma Management System!")
                elif choi==4:
                    cuid=input("\t\tEnter Customer Id to update record      : ")
                    npq=input("\t\tEnter updated product quantity          : ")
                    q="update customer set pdt_qty='{}' where cuid='{}'".format(npq,cuid)
                    sqlcur.execute(q)
                    sqlcon.commit()
                    print("Customer order updated successfully!")
                    print("Thanks for using Dawa Pharma Management System!")
                else:
                    print("Choice is invalid!")
                    print("Thanks for using Dawa Pharma Management System!")
                    exit(1)
            elif cho==4:
                cuid=input("\t\tEnter Customer Id to delete order record      : ")
                q="delete from customer where cuid='{}'".format(cuid)
                sqlcur.execute(q)
                sqlcon.commit()
                print("Customer order record of cuid",cuid,"has been deleted successfully!")
                print("Thanks for using Dawa Pharma Management System!")
            else:
                print("Choice is invalid!")
                print("Thanks for using Dawa Pharma Management System!")
        elif opt==6:
            print("Thanks for using Dawa Pharma Management System!")
        else:
            print("Choice is invalid!")
            print("Thanks for using Dawa Pharma Management System!")
elif ch==2: 
    print("\n\t\t\t\tUser SignUp")
    uid=input("\n\t\t\tEnter UserId     :   ")
    pas=input("\t\t\tEnter Password   :   ")
    q="insert into users values('{}','{}')".format(uid,pas)
    sqlcur.execute(q)
    sqlcon.commit()
    print("Thanks for signing up!")
else:
    print("choice is invalid!")
    print("Thanks for visiting Dawa Pharma!")